/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bamboo_Module */

#ifndef _Included_bamboo_Module
#define _Included_bamboo_Module
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bamboo_Module
 * Method:    readDCFile
 * Signature: (Ljava/lang/String;)Lbamboo/Module;
 */
JNIEXPORT jobject JNICALL Java_bamboo_Module_readDCFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bamboo_Module
 * Method:    parseDCFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_bamboo_Module_parseDCFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bamboo_Module
 * Method:    calculateHash
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bamboo_Module_calculateHash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
